# Generated by Django 3.0.8 on 2020-07-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casas',
            name='valor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
