# Generated by Django 3.0.8 on 2020-07-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_casas_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='casas',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
