# Generated by Django 3.0.8 on 2020-07-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_casas_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('slider', models.FileField(blank=True, help_text='1884x529', null=True, upload_to='slider')),
            ],
            options={
                'verbose_name_plural': '1. Slider',
            },
        ),
    ]
