# Generated by Django 3.0.8 on 2020-07-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto_empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('mapa', models.TextField(blank=True, max_length=500, null=True)),
                ('representante', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_personal', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('celular2', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('horario', models.CharField(blank=True, default=1, max_length=100, null=True)),
                ('horariosb', models.CharField(blank=True, default=1, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Contacto Empresa',
            },
        ),
        migrations.CreateModel(
            name='Redes_sociales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('behance', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Redes Sociales',
            },
        ),
        migrations.CreateModel(
            name='Zatuar_marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='empresa/logo/')),
                ('logo_blanco', models.FileField(blank=True, null=True, upload_to='empresa/logo/')),
                ('logo_negro', models.FileField(blank=True, null=True, upload_to='empresa/logo/')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='empresa/logo/')),
                ('imagen', models.FileField(blank=True, help_text='400x400', null=True, upload_to='empresa/logo/')),
                ('portada', models.FileField(blank=True, help_text='1280x400', null=True, upload_to='empresa/logo/')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '2. Zatuar Marca',
            },
        ),
    ]
