# Generated by Django 3.0.8 on 2020-07-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_contacto_empresa_redes_sociales_zatuar_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficio', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Zatuar Beneficios',
            },
        ),
        migrations.CreateModel(
            name='Descarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('principal', models.BooleanField(default=False)),
                ('img', models.FileField(blank=True, null=True, upload_to='descarga')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='descarga')),
            ],
            options={
                'verbose_name_plural': '8. Descarga',
            },
        ),
        migrations.CreateModel(
            name='Galeria_Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='inicio')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': '7. Galeria_Proceso',
            },
        ),
        migrations.CreateModel(
            name='Identidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': '5. Zatuar es',
            },
        ),
        migrations.CreateModel(
            name='Personalizaion_Poducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='producto')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Perzonalizacion de Productos',
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=200, null=True)),
                ('img1', models.FileField(blank=True, null=True, upload_to='inicio')),
                ('ti1', models.CharField(blank=True, max_length=30, null=True)),
                ('img2', models.FileField(blank=True, null=True, upload_to='inicio')),
                ('ti2', models.CharField(blank=True, max_length=30, null=True)),
                ('img3', models.FileField(blank=True, null=True, upload_to='inicio')),
                ('ti3', models.CharField(blank=True, max_length=30, null=True)),
                ('ti4', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': '6. Proceso',
            },
        ),
    ]
