# Generated by Django 3.0.8 on 2020-07-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=40, null=True)),
                ('nombre_export', models.CharField(blank=True, max_length=100, null=True)),
                ('client_logo', models.FileField(blank=True, help_text='200x200', null=True, upload_to='cliente')),
                ('detalle', models.TextField(blank=True, max_length=500, null=True)),
                ('foto', models.FileField(blank=True, help_text='1280x500', null=True, upload_to='cliente')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('pagweb', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '8. Clientes',
            },
        ),
        migrations.CreateModel(
            name='Producto_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_producto', models.FileField(blank=True, help_text='500x500', null=True, upload_to='producto')),
                ('portada', models.FileField(blank=True, help_text='600x400', null=True, upload_to='producto')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clientes.Cliente')),
            ],
            options={
                'verbose_name_plural': '7. Mandil Cliente',
            },
        ),
        migrations.CreateModel(
            name='Galeria_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galeria', models.FileField(blank=True, help_text='500x500', null=True, upload_to='cliente')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clientes.Cliente')),
            ],
            options={
                'verbose_name_plural': '9.a Cliente Galeria',
            },
        ),
    ]
